spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/team3
    username: sa
    password:
    driver-class-name: org.h2.Driver

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true


logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.type: warn

server:
  servlet:
    session:
      tracking-modes: cookie

decorator:
  datasource:
    p6spy:
      enable-logging: false
